# Generated by Django 4.1 on 2023-01-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='chapter',
            field=models.CharField(default='001', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlepost',
            name='depart',
            field=models.CharField(default='ue', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlepost',
            name='img_path',
            field=models.CharField(default='imgs', max_length=100),
            preserve_default=False,
        ),
    ]
