# Generated by Django 4.1 on 2023-01-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articlepost_author_alter_articlepost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='subject',
            field=models.CharField(default='001', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='img_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
